Repository Chitresh-code/DSA_Worksheet, pull requests merged in 2023-10, with the labels that each got.

#2 Selection Sort using cpp
  DSA_Codesheet/Cpp/Selection_Sort.cpp
Labels: good first issue, question, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted, C++, Level: Easy

#16 Create selection_sort.c
  DSA_Codesheet/C/selection_sort.c
Labels: good first issue, question, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted, C, Level: Easy

#34 sort012 with c++ - Lilmistake DSA Worksheet
  DSA_Codesheet/Cpp/sort012.cpp
Labels: good first issue, question, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted, C++, Level: Medium

#35 sort012 with c - Lilmistake DSA Worksheet
  DSA_Codesheet/C/sort012.c
Labels: good first issue, question, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted, C, Level: Medium

#38 Update issue templates
  .github/ISSUE_TEMPLATE/dsa-question-template.md
Labels: bug, help wanted, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#40 Added more info in the README and CONTRIBUTING Files
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  README.md
Labels: documentation, help wanted, good first issue, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#43 Chitresh code patch 3
  .github/workflows/main.yml
  README.md
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted

#45 provided the code of pascal's triangle in cpp
  DSA_Codesheet/Cpp/pascalTriangle.cpp
Labels: good first issue, question, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted, C++, Level: Hard

#78 Adding triplet sum code
  DSA_Codesheet/Java/Triplet_Sum.java
Labels: good first issue, question, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted, Java, Level: Medium

#79 Adding search in rotated sorted array
  DSA_Codesheet/Java/SearchRotatedSorted.java
Labels: good first issue, question, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted, Java, Level: Medium

#77 #75 Add. Triplet sum in array
  DSA_Codesheet/Cpp/triplet_sum.cpp
  DSA_Codesheet/Cpp/triplet_sum.exe
Labels: good first issue, question, hacktoberfest, hacktoberfest-2023, hacktoberfest-accepted, C++, Level: Medium

#63 added counting sort in python
  DSA_Codesheet/Python/countingSort.py
Labels: changes requested
